### ISSUE TITLE
Causal effect difference/ratios bootstrapping functions 

### ISSUE THREAD

**Issue by alockhar** [RobinDenz1/contsurvplot#10]
First, this package has been wonderful so far after taking me a while to grasp g-computation within the context of a continuous exposure in a time-to-event setting. Thank you so much.

I was curious about some of the functions in the bootstrapping of the causal differences/ratios in the appendix. Basically I’ve been doing my own test run on my own problem but haven’t been successful with this piece.

1. I figured ‘get_boot_sample’ was assigning an id based on the initial sequence?  So if 1000 bootstraps in 4 models, it then assigns an indicator of 1 to 4000 across a dataset of 4000 separate observations? Is this a homemade function or one that is found in another imported package?

2. Were the functions ‘get_contrast’ and ‘apply_get_contrast_model’ homemade functions? Or imported ones from another package?  

Any assistance would be great as I figure out my final test run of these pieces.

**Comment by RobinDenz1** [comment]
Thank you for the kind words. I am assuming you are talking about the code in the appendix of the associated article. Both functions were written by me and should be included in the appendix as well. I have, however, re-factored the code given there and included its full functionality in the current version of `contsurvplot`. The code used in the package is probably a lot easier to follow and it is covered by the automatic tests as well, so I would highly advise using this code. You can check it out right here on github (file "curve_cont.r", starting from line 89).
