### ISSUE TITLE
Overlay multiple plot_surv_at_t 

### ISSUE THREAD

**Issue by ArighnoDas** [RobinDenz1/contsurvplot#2]
Hi, 

Love this package. I have some survival data and I was wondering if theres a way to overlay two plot_surv_at_t plots in one graph

Currently I have one plot with recurrence free survival with a continuous variable of size and a second plot of cancer specific survival with a continuous variable of size. Both are 5-year. Is there a way the two could be shown in the same plot? 

Thanks!
Arighno

**Comment by ArighnoDas** [comment]
Additionally, how do I change the y-axis scale? I'm trying to use scale_y_continuous but not having success. But am able to change the x-axis using scale_x_continuous just fine.

**Comment by RobinDenz1** [comment]
Hi Arighno,

thank you for the kind words.

There is no direct way to do this with the `contsurvplot` package, but you can still get what you are looking for quite easily. As i see it you have two options:

1.) Call the `plot_surv_at_t` function twice, saving the output and combine the plots using a function such as `ggarrange` from the `ggpubr` package. This probably is not exactly what you are looking for though.

2.) Call the `curve_cont` function directly to obtain the required data for both plots. This is done internally by all plot functions of this package. You can then combine them in one `data.frame` and use your own small plot function to depict the results. Here is an example of what this might look like:
```
library(contsurvplot)
library(ggplot2)
library(survival)

data(nafld, package="survival")

# take a random sample to keep example fast
set.seed(42)
nafld1 <- nafld1[sample(nrow(nafld1), 150), ]

# fit two models
model_1 <- coxph(Surv(futime, status) ~ age, data=nafld1, x=TRUE)
model_2 <- coxph(Surv(futime, status) ~ age + I(age^2), data=nafld1, x=TRUE)

# get marginal survival probability estimates at t = 2000 for both models
est_1 <- curve_cont(time="futime",
                    status="status",
                    variable="age",
                    data=nafld1,
                    model=model_1,
                    times=2000,
                    horizon=seq(20, 88, 1))
est_2 <- curve_cont(time="futime",
                    status="status",
                    variable="age",
                    data=nafld1,
                    model=model_2,
                    times=2000,
                    horizon=seq(20, 88, 1))

# combine into one data.frame
est_1$model <- "Model 1"
est_2$model <- "Model 2"
plotdata <- rbind(est_1, est_2)

# plot its using custom code
ggplot(plotdata, aes(x=cont, y=est, color=model)) +
  geom_line() +
  theme_bw() +
  labs(x="Age", y="Survival Probability at t = 2000")
```
The documentation of the `curve_cont` function may be useful to you if you want to do this. If you have any further questions or suggestions, please let me know! And please consider citing the paper associated with this package if you end up using it.

With kind regards,
Robin

**Comment by ArighnoDas** [comment]
Thank you for the detailed response! This works great!
